import { expect, test } from '@playwright/test';

// Run against a production build: pnpm build:web && PORT=5188 pnpm start
// POIETRA_TEST_URL=http://127.0.0.1:5188 pnpm exec playwright test dogfood-home-seo
test.skip(!process.env.POIETRA_TEST_URL, 'Prerendered HTML is generated by the production build.');

test('English and Japanese product pages remain readable without JavaScript', async ({ browser }) => {
  const context = await browser.newContext({ javaScriptEnabled: false, locale: 'en-US' });
  try {
    const page = await context.newPage();
    for (const [path, locale, description] of [['/?lang=en', 'en', 'Your idea.'], ['/ja/', 'ja', 'ひとりのアイデアを、']] as const) {
      const response = await page.goto(path);
      expect(response?.status()).toBe(200);
      await expect(page.locator('html')).toHaveAttribute('lang', locale);
      await expect(page.getByRole('heading', { level: 1 })).toHaveText('Motion,together.');
      await expect(page.locator('.landing-hero-statement')).toContainText(description);
      await expect(page.locator('link[rel="canonical"]')).toHaveAttribute('href', `https://poietra.com/${locale === 'ja' ? 'ja/' : ''}`);
      const schema = JSON.parse((await page.locator('script[type="application/ld+json"]').textContent())!);
      expect(schema['@type']).toBe('WebApplication'); expect(schema.inLanguage).toBe(locale);
    }
  } finally { await context.close(); }
});

test('crawler endpoints and negotiated Markdown return public content with correct types', async ({ request }) => {
  for (const [path, mime, text] of [['/robots.txt', 'text/plain', 'Sitemap:'], ['/sitemap.xml', 'xml', '<urlset'], ['/llms.txt', 'text/plain', '# Poietra'], ['/index.md', 'text/markdown', '# Poietra']] as const) {
    const response = await request.get(path);
    expect(response.status()).toBe(200); expect(response.headers()['content-type']).toContain(mime);
    expect(await response.text()).toContain(text); expect(await response.text()).not.toContain('<div id="root"');
  }
  const markdown = await request.get('/?lang=ja', { headers: { Accept: 'text/markdown' } });
  expect(markdown.headers()['content-type']).toContain('text/markdown');
  expect(markdown.headers().vary).toContain('Accept');
  expect(await markdown.text()).toContain('友人と、AIと。');
  const html = await request.get('/', { headers: { Accept: 'text/markdown;q=0, text/html' } });
  expect(html.headers()['content-type']).toContain('text/html');
});

test('editor entry HTML is noindex and keeps project URLs out of marketing pages', async ({ request }) => {
  for (const path of ['/studio', '/?room=seo_read_only_probe_001', '/?projects=1']) {
    const response = await request.get(path);
    expect(response.status()).toBe(200);
    expect(response.headers()['x-robots-tag']).toContain('noindex');
    expect(await response.text()).toContain('name="robots" content="noindex');
    expect(await response.text()).not.toContain('id="landing-title"');
  }
  const missing = await request.get('/not-a-poietra-page');
  expect(missing.status()).toBe(404);
});

test('hydration keeps the static page and limits Japanese font requests', async ({ page }) => {
  const errors: string[] = [], fonts: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
  page.on('request', request => { if (/\.woff2?(?:\?|$)/.test(request.url())) fonts.push(request.url()); });
  await page.goto('/ja/?lang=invalid');
  await expect(page.getByRole('button', { name: '新しいプロジェクト', exact: true })).toBeVisible();
  const slider = page.getByRole('slider', { name: '動きのデモの再生位置', exact: true });
  await slider.focus(); await slider.press('End');
  await expect(slider).toHaveValue('2000');
  await page.evaluate(() => document.fonts.ready);
  expect(fonts.length).toBeLessThanOrEqual(4);
  expect(errors).toEqual([]);
});
